import {
  cilApplicationsSettings,
  cilMenu,
  cilSpeedometer,
  cilEnvelopeOpen,
  cilLockLocked,
  cilAccountLogout,
  cilUser,
  cilOptions,
  cilDelete,
  cilArrowTop,
  cilSun,
  cilMoon,
  cilFile,
  cilCreditCard,
  cilTask,
  cilBell,
  cilCommentSquare,
  cilSettings,
  cifTr,
  cifUs,
  cifBr,
  cifGb
} from '@coreui/icons';

export const iconSubset = {
  cilApplicationsSettings,
  cilMenu,
  cilSpeedometer,
  cilEnvelopeOpen,
  cilLockLocked,
  cilAccountLogout,
  cilUser,
  cilOptions,
  cilDelete,
  cilArrowTop,
  cilSun,
  cilMoon,
  cilFile,
  cilCreditCard,
  cilTask,
  cilBell,
  cilCommentSquare,
  cilSettings,
  cifTr,
  cifUs,
  cifBr,
  cifGb
};

export enum IconSubset {
  cilApplicationsSettings = 'cilApplicationsSettings',
  cilMenu = 'cilMenu',
  cilSpeedometer = 'cilSpeedometer',
  cilEnvelopeOpen = 'cilEnvelopeOpen',
  cilLockLocked = 'cilLockLocked',
  cilAccountLogout = 'cilAccountLogout',
  cilUser = 'cilUser',
  cilOptions = 'cilOptions',
  cilDelete = 'cilDelete',
  cilArrowTop = 'cilArrowTop',
  cilSun = 'cilSun',
  cilMoon = 'cilMoon',
  cilFile = 'cilFile',
  cilCreditCard = 'cilCreditCard',  
  cilTask = 'cilTask',
  cilBell = 'cilBell',
  cilCommentSquare = 'cilCommentSquare',
  cilSettings = 'cilSettings',
  cifTr = 'cifTr',
  cifUs = 'cifUs',
  cifBr = 'cifBr',
  cifGb = 'cifGb'
}
